/**
 * Seed data for ECP (Empowerment Community Platform) Lagos.
 * 
 * This file contains realistic mock data for all entities.
 * It is consumed by the SeedProvider on first load.
 */

import type { User } from "../models/user";
import type { MembershipApplication } from "../models/membership";
import type { Event } from "../models/event";
import type { RSVP } from "../models/rsvp";
import type { NewsPost } from "../models/news";
import type { Committee } from "../models/committee";
import type { Product } from "../models/product";
import type { Order } from "../models/order";
import type { Donation } from "../models/donation";

/* â”€â”€â”€ Users â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
export const SEED_USERS: User[] = [
  {
    id: "u-admin-001",
    email: "admin@ekoclubphiladelphia.org",
    firstName: "Chidi",
    lastName: "Okonkwo",
    displayName: "Chidi Okonkwo",
    role: "super-admin",
    status: "active",
    avatarUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Chidi",
    phone: "08012345678",
    lga: "Ikeja",
    ward: "Alausa Ward",
    occupation: "Platform Administrator",
    bio: "Platform administrator and founding member of Eko Club Philadelphia.",
    joinedAt: "2023-01-15T08:00:00.000Z",
    lastLoginAt: "2026-05-05T10:00:00.000Z",
  },
  {
    id: "u-admin-002",
    email: "secretary@ekoclubphiladelphia.org",
    firstName: "Amaka",
    lastName: "Eze",
    displayName: "Amaka Eze",
    role: "admin",
    status: "active",
    avatarUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Amaka",
    phone: "08023456789",
    lga: "Lagos Island",
    ward: "Campos Ward",
    occupation: "Community Organizer",
    bio: "General Secretary, Eko Club Philadelphia. Passionate about cultural education.",
    joinedAt: "2023-02-10T08:00:00.000Z",
    lastLoginAt: "2026-05-04T14:00:00.000Z",
    membershipId: "ma-001",
  },
  {
    id: "u-member-001",
    email: "tunde.adeyemi@email.com",
    firstName: "Tunde",
    lastName: "Adeyemi",
    displayName: "Tunde Adeyemi",
    role: "member",
    status: "active",
    avatarUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Tunde",
    phone: "08034567890",
    lga: "Surulere",
    ward: "Ijeshatedo Ward",
    occupation: "Software Engineer",
    bio: "Tech professional committed to digital transformation in governance.",
    joinedAt: "2023-06-20T08:00:00.000Z",
    lastLoginAt: "2026-05-03T09:00:00.000Z",
    membershipId: "ma-002",
  },
  {
    id: "u-member-002",
    email: "ngozi.obi@email.com",
    firstName: "Ngozi",
    lastName: "Obi",
    displayName: "Ngozi Obi",
    role: "member",
    status: "active",
    avatarUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Ngozi",
    phone: "08045678901",
    lga: "Eti-Osa",
    ward: "Lekki Phase 1 Ward",
    occupation: "Lawyer",
    bio: "Legal practitioner focused on constitutional rights and electoral law.",
    joinedAt: "2023-08-15T08:00:00.000Z",
    lastLoginAt: "2026-05-01T11:00:00.000Z",
    membershipId: "ma-003",
  },
  {
    id: "u-member-003",
    email: "emeka.uche@email.com",
    firstName: "Emeka",
    lastName: "Uche",
    displayName: "Emeka Uche",
    role: "member",
    status: "active",
    avatarUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Emeka",
    phone: "08056789012",
    lga: "Alimosho",
    ward: "Idimu Ward",
    occupation: "Teacher",
    bio: "Secondary school educator advocating for quality public education in Lagos.",
    joinedAt: "2023-10-01T08:00:00.000Z",
    lastLoginAt: "2026-04-28T15:00:00.000Z",
    membershipId: "ma-004",
  },
  {
    id: "u-member-004",
    email: "fatima.sule@email.com",
    firstName: "Fatima",
    lastName: "Sule",
    displayName: "Fatima Sule",
    role: "member",
    status: "active",
    avatarUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Fatima",
    phone: "08067890123",
    lga: "Kosofe",
    ward: "Agboyi Ward",
    occupation: "Public Health Worker",
    bio: "Dedicated to improving healthcare access in underserved Lagos communities.",
    joinedAt: "2024-01-10T08:00:00.000Z",
    lastLoginAt: "2026-05-02T13:00:00.000Z",
    membershipId: "ma-005",
  },
  {
    id: "u-applicant-001",
    email: "babatunde.lawal@email.com",
    firstName: "Babatunde",
    lastName: "Lawal",
    displayName: "Babatunde Lawal",
    role: "applicant",
    status: "pending",
    avatarUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Babatunde",
    phone: "08078901234",
    lga: "Mushin",
    ward: "Mushin Ward 1",
    occupation: "Entrepreneur",
    joinedAt: "2026-04-20T08:00:00.000Z",
  },
  {
    id: "u-applicant-002",
    email: "adaeze.nwosu@email.com",
    firstName: "Adaeze",
    lastName: "Nwosu",
    displayName: "Adaeze Nwosu",
    role: "applicant",
    status: "pending",
    avatarUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Adaeze",
    phone: "08089012345",
    lga: "Ajegunle",
    occupation: "Journalist",
    joinedAt: "2026-04-25T08:00:00.000Z",
  },
];

/* â”€â”€â”€ Membership Applications â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
export const SEED_APPLICATIONS: MembershipApplication[] = [
  {
    id: "ma-001",
    fullName: "Amaka Eze",
    email: "secretary@ekoclubphiladelphia.org",
    phone: "08023456789",
    lga: "Lagos Island",
    ward: "Campos Ward",
    occupation: "Community Organizer",
    reasonForJoining: "I want to contribute to cultural education and grassroots democracy in Lagos.",
    areasOfInterest: ["civic-education", "community-organizing", "women-leadership"],
    hasVolunteered: true,
    status: "approved",
    appliedAt: "2023-02-08T08:00:00.000Z",
    reviewedAt: "2023-02-10T08:00:00.000Z",
    reviewedBy: "u-admin-001",
    reviewNotes: "Outstanding candidate. Approved.",
    userId: "u-admin-002",
  },
  {
    id: "ma-002",
    fullName: "Tunde Adeyemi",
    email: "tunde.adeyemi@email.com",
    phone: "08034567890",
    lga: "Surulere",
    ward: "Ijeshatedo Ward",
    occupation: "Software Engineer",
    reasonForJoining: "I believe technology can transform local governance and I want to help ECP leverage it.",
    areasOfInterest: ["digital-governance", "youth-empowerment", "tech-for-good"],
    hasVolunteered: false,
    status: "approved",
    appliedAt: "2023-06-15T08:00:00.000Z",
    reviewedAt: "2023-06-20T08:00:00.000Z",
    reviewedBy: "u-admin-001",
    userId: "u-member-001",
  },
  {
    id: "ma-003",
    fullName: "Ngozi Obi",
    email: "ngozi.obi@email.com",
    phone: "08045678901",
    lga: "Eti-Osa",
    ward: "Lekki Phase 1 Ward",
    occupation: "Lawyer",
    reasonForJoining: "Electoral law is my specialty. I want to help members understand their rights and hold officials accountable.",
    areasOfInterest: ["electoral-law", "advocacy", "anti-corruption"],
    hasVolunteered: true,
    referredBy: "Tunde Adeyemi",
    status: "approved",
    appliedAt: "2023-08-10T08:00:00.000Z",
    reviewedAt: "2023-08-15T08:00:00.000Z",
    reviewedBy: "u-admin-002",
    userId: "u-member-002",
  },
  {
    id: "ma-004",
    fullName: "Emeka Uche",
    email: "emeka.uche@email.com",
    phone: "08056789012",
    lga: "Alimosho",
    ward: "Idimu Ward",
    occupation: "Teacher",
    reasonForJoining: "Education drives everything. I want to help equip Lagos youth with civic knowledge.",
    areasOfInterest: ["education", "youth-empowerment", "civic-education"],
    hasVolunteered: true,
    status: "approved",
    appliedAt: "2023-09-25T08:00:00.000Z",
    reviewedAt: "2023-10-01T08:00:00.000Z",
    reviewedBy: "u-admin-002",
    userId: "u-member-003",
  },
  {
    id: "ma-005",
    fullName: "Fatima Sule",
    email: "fatima.sule@email.com",
    phone: "08067890123",
    lga: "Kosofe",
    ward: "Agboyi Ward",
    occupation: "Public Health Worker",
    reasonForJoining: "Community health starts with engaged citizens. I want to bridge health advocacy with civic action.",
    areasOfInterest: ["healthcare", "community-development", "women-leadership"],
    hasVolunteered: true,
    status: "approved",
    appliedAt: "2024-01-05T08:00:00.000Z",
    reviewedAt: "2024-01-10T08:00:00.000Z",
    reviewedBy: "u-admin-001",
    userId: "u-member-004",
  },
  {
    id: "ma-006",
    fullName: "Babatunde Lawal",
    email: "babatunde.lawal@email.com",
    phone: "08078901234",
    lga: "Mushin",
    ward: "Mushin Ward 1",
    occupation: "Entrepreneur",
    reasonForJoining: "As a small business owner in Mushin, I see how local policies directly impact livelihoods. I want to be part of the change.",
    areasOfInterest: ["economic-empowerment", "small-business", "youth-empowerment"],
    hasVolunteered: false,
    status: "under-review",
    appliedAt: "2026-04-20T08:00:00.000Z",
    userId: "u-applicant-001",
  },
  {
    id: "ma-007",
    fullName: "Adaeze Nwosu",
    email: "adaeze.nwosu@email.com",
    phone: "08089012345",
    lga: "Ajegunle",
    occupation: "Journalist",
    reasonForJoining: "Journalism needs civic partnership. I want to help ECP tell Lagos stories accurately.",
    areasOfInterest: ["media", "civic-education", "anti-corruption"],
    hasVolunteered: true,
    status: "pending",
    appliedAt: "2026-04-25T08:00:00.000Z",
    userId: "u-applicant-002",
  },
];

/* â”€â”€â”€ Events â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
export const SEED_EVENTS: Event[] = [
  {
    id: "ev-001",
    title: "Lagos Civic Town Hall 2026",
    slug: "lagos-civic-town-hall-2026",
    description: "Join Eko Club Philadelphia for our flagship annual town hall bringing together citizens, community leaders, and elected officials to discuss the state of Lagos governance. Topics: infrastructure, education, healthcare, and accountability.",
    shortDescription: "Annual town hall connecting citizens with Lagos leaders.",
    date: "2026-06-14T10:00:00.000Z",
    endDate: "2026-06-14T16:00:00.000Z",
    time: "10:00 AM",
    endTime: "4:00 PM",
    location: "Lagos State House of Assembly Complex, Alausa, Ikeja",
    venue: "Main Auditorium",
    isOnline: false,
    type: "town-hall",
    status: "published",
    imageUrl: "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=800",
    maxAttendees: 500,
    registrationRequired: true,
    registrationDeadline: "2026-06-10T23:59:00.000Z",
    organizerId: "u-admin-001",
    organizerName: "Eko Club Philadelphia",
    tags: ["governance", "accountability", "town-hall", "lagos"],
    isFeatured: true,
    isPublic: true,
    createdAt: "2026-03-01T08:00:00.000Z",
    updatedAt: "2026-04-15T08:00:00.000Z",
  },
  {
    id: "ev-002",
    title: "Digital Skills for Civic Advocacy Workshop",
    slug: "digital-skills-civic-advocacy-workshop",
    description: "Learn how to use digital tools â€” social media, data journalism, and online petitions â€” to amplify your civic voice. Hands-on sessions led by expert trainers.",
    shortDescription: "Hands-on digital tools training for civic advocates.",
    date: "2026-05-24T09:00:00.000Z",
    endDate: "2026-05-24T13:00:00.000Z",
    time: "9:00 AM",
    endTime: "1:00 PM",
    location: "Co-Creation Hub, Yaba, Lagos",
    isOnline: false,
    type: "workshop",
    status: "published",
    imageUrl: "https://images.unsplash.com/photo-1531058020387-3be344556be6?w=800",
    maxAttendees: 80,
    registrationRequired: true,
    organizerId: "u-member-001",
    organizerName: "Tunde Adeyemi",
    tags: ["digital", "workshop", "advocacy", "social-media"],
    isFeatured: true,
    isPublic: true,
    createdAt: "2026-04-01T08:00:00.000Z",
    updatedAt: "2026-04-20T08:00:00.000Z",
  },
  {
    id: "ev-003",
    title: "Victoria Island Community Meetup",
    slug: "vi-community-meetup-may-2026",
    description: "Monthly community meetup for ECP members in the Victoria Island / Eti-Osa axis. Network, share ideas, and get updates on local projects.",
    shortDescription: "Monthly member meetup in Victoria Island.",
    date: "2026-05-18T17:00:00.000Z",
    endDate: "2026-05-18T19:00:00.000Z",
    time: "5:00 PM",
    endTime: "7:00 PM",
    location: "The Wheatbaker Hotel, Ikoyi, Lagos",
    isOnline: false,
    type: "meetup",
    status: "published",
    maxAttendees: 50,
    registrationRequired: true,
    organizerId: "u-member-002",
    organizerName: "Ngozi Obi",
    tags: ["meetup", "networking", "ikoyi", "members"],
    isFeatured: false,
    isPublic: false,
    createdAt: "2026-04-28T08:00:00.000Z",
    updatedAt: "2026-04-28T08:00:00.000Z",
  },
  {
    id: "ev-004",
    title: "Environmental Advocacy Volunteer Day",
    slug: "environmental-advocacy-volunteer-day",
    description: "Join hands with other ECP volunteers for a community clean-up and environmental awareness campaign in Alimosho. We will also plant trees and host a mini-fair for residents.",
    shortDescription: "Community clean-up and environmental awareness volunteer day.",
    date: "2026-05-30T08:00:00.000Z",
    endDate: "2026-05-30T14:00:00.000Z",
    time: "8:00 AM",
    endTime: "2:00 PM",
    location: "Iyana-Ipaja Bus Terminal, Alimosho, Lagos",
    isOnline: false,
    type: "volunteer",
    status: "published",
    maxAttendees: 200,
    registrationRequired: true,
    organizerId: "u-member-003",
    organizerName: "Emeka Uche",
    tags: ["environment", "volunteer", "alimosho", "community"],
    isFeatured: false,
    isPublic: true,
    createdAt: "2026-04-10T08:00:00.000Z",
    updatedAt: "2026-04-10T08:00:00.000Z",
  },
  {
    id: "ev-005",
    title: "Know Your Rights: Electoral Law Seminar",
    slug: "know-your-rights-electoral-law-seminar-2026",
    description: "A comprehensive seminar on Nigerian electoral law, voter rights, and how to report electoral malpractice. Facilitated by ECP Legal Committee.",
    shortDescription: "Learn your electoral rights and how to report violations.",
    date: "2026-06-07T10:00:00.000Z",
    endDate: "2026-06-07T15:00:00.000Z",
    time: "10:00 AM",
    endTime: "3:00 PM",
    location: "Online (Zoom)",
    isOnline: true,
    meetingUrl: "https://zoom.us/j/ecp-electoral-seminar",
    type: "seminar",
    status: "published",
    maxAttendees: 300,
    registrationRequired: true,
    organizerId: "u-member-002",
    organizerName: "Ngozi Obi",
    tags: ["law", "electoral", "rights", "seminar", "online"],
    isFeatured: true,
    isPublic: true,
    createdAt: "2026-04-18T08:00:00.000Z",
    updatedAt: "2026-05-01T08:00:00.000Z",
  },
  {
    id: "ev-006",
    title: "Community Health Fair â€” Kosofe Edition",
    slug: "community-health-fair-kosofe-2026",
    description: "Free health screenings, health education, and community resource fair for Kosofe residents. Partnering with local clinics and NGOs.",
    shortDescription: "Free health screenings and health education for Kosofe community.",
    date: "2026-06-21T09:00:00.000Z",
    endDate: "2026-06-21T17:00:00.000Z",
    time: "9:00 AM",
    endTime: "5:00 PM",
    location: "Kosofe Local Government Secretariat, Lagos",
    isOnline: false,
    type: "volunteer",
    status: "published",
    maxAttendees: 1000,
    registrationRequired: false,
    organizerId: "u-member-004",
    organizerName: "Fatima Sule",
    tags: ["health", "community", "kosofe", "free"],
    isFeatured: false,
    isPublic: true,
    createdAt: "2026-04-22T08:00:00.000Z",
    updatedAt: "2026-04-22T08:00:00.000Z",
  },
  {
    id: "ev-007",
    title: "ECP Annual Gala Dinner 2025",
    slug: "ecp-annual-gala-2025",
    description: "Our annual celebration of civic excellence, recognizing outstanding contributors and launching the year's fundraising campaign.",
    shortDescription: "ECP 2025 Annual Gala â€” celebrating civic excellence.",
    date: "2025-12-07T18:00:00.000Z",
    endDate: "2025-12-07T22:00:00.000Z",
    time: "6:00 PM",
    endTime: "10:00 PM",
    location: "Eko Hotels & Suites, Victoria Island, Lagos",
    isOnline: false,
    type: "meetup",
    status: "completed",
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800",
    maxAttendees: 300,
    registrationRequired: true,
    organizerId: "u-admin-001",
    organizerName: "Eko Club Philadelphia",
    tags: ["gala", "fundraising", "awards", "annual"],
    isFeatured: false,
    isPublic: true,
    createdAt: "2025-10-01T08:00:00.000Z",
    updatedAt: "2025-12-08T08:00:00.000Z",
  },
];

/* â”€â”€â”€ RSVPs â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
export const SEED_RSVPS: RSVP[] = [
  {
    id: "rsvp-001",
    eventId: "ev-001",
    userId: "u-member-001",
    name: "Tunde Adeyemi",
    email: "tunde.adeyemi@email.com",
    phone: "08034567890",
    status: "confirmed",
    registeredAt: "2026-04-02T09:00:00.000Z",
  },
  {
    id: "rsvp-002",
    eventId: "ev-001",
    userId: "u-member-002",
    name: "Ngozi Obi",
    email: "ngozi.obi@email.com",
    status: "confirmed",
    registeredAt: "2026-04-03T10:00:00.000Z",
  },
  {
    id: "rsvp-003",
    eventId: "ev-001",
    userId: "u-member-003",
    name: "Emeka Uche",
    email: "emeka.uche@email.com",
    status: "confirmed",
    registeredAt: "2026-04-04T11:00:00.000Z",
  },
  {
    id: "rsvp-004",
    eventId: "ev-002",
    userId: "u-member-004",
    name: "Fatima Sule",
    email: "fatima.sule@email.com",
    status: "confirmed",
    registeredAt: "2026-04-10T08:00:00.000Z",
  },
  {
    id: "rsvp-005",
    eventId: "ev-002",
    userId: "u-member-001",
    name: "Tunde Adeyemi",
    email: "tunde.adeyemi@email.com",
    status: "confirmed",
    registeredAt: "2026-04-12T09:00:00.000Z",
  },
  {
    id: "rsvp-006",
    eventId: "ev-003",
    userId: "u-member-002",
    name: "Ngozi Obi",
    email: "ngozi.obi@email.com",
    status: "confirmed",
    registeredAt: "2026-05-01T10:00:00.000Z",
  },
  {
    id: "rsvp-007",
    eventId: "ev-005",
    name: "Samuel Adeola",
    email: "samuel.adeola@email.com",
    phone: "08099887766",
    status: "confirmed",
    registeredAt: "2026-04-20T14:00:00.000Z",
  },
  {
    id: "rsvp-008",
    eventId: "ev-005",
    userId: "u-member-003",
    name: "Emeka Uche",
    email: "emeka.uche@email.com",
    status: "confirmed",
    registeredAt: "2026-04-22T15:00:00.000Z",
  },
];

/* â”€â”€â”€ News Posts â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
export const SEED_NEWS: NewsPost[] = [
  {
    id: "news-001",
    title: "Eko Club Philadelphia Launches 2026 cultural education Campaign",
    slug: "ecp-launches-2026-civic-education-campaign",
    excerpt: "Eko Club Philadelphia has officially launched its ambitious 2026 cultural education Campaign, targeting over 50,000 Lagos residents across all 20 LGAs.",
    content: `<p>Eko Club Philadelphia has officially launched its ambitious 2026 cultural education Campaign, targeting over 50,000 Lagos residents across all 20 local government areas.</p><p>The campaign, themed <strong>"Know Your Lagos"</strong>, will use a combination of community town halls, school outreach programmes, and digital content to equip Lagosians with the knowledge they need to participate meaningfully in governance.</p><p>"We believe an informed citizenry is the foundation of accountable governance," said Eko Club Philadelphia Chair Chidi Okonkwo at the launch event. "This campaign is our commitment to that belief."</p><p>The campaign will run from May through December 2026 and includes a partnership with 10 secondary schools in underserved communities.</p>`,
    category: "announcement",
    status: "published",
    imageUrl: "https://images.unsplash.com/photo-1529390079861-591de354faf5?w=800",
    imageAlt: "Eko Club Philadelphia cultural education Campaign launch",
    authorId: "u-admin-001",
    authorName: "Chidi Okonkwo",
    authorAvatarUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Chidi",
    viewCount: 1842,
    readingTimeMinutes: 3,
    isFeatured: true,
    isBreaking: false,
    isPinned: true,
    tags: ["civic-education", "campaign", "2026", "lagos"],
    publishedAt: "2026-05-01T08:00:00.000Z",
    createdAt: "2026-04-28T08:00:00.000Z",
    updatedAt: "2026-05-01T08:00:00.000Z",
  },
  {
    id: "news-002",
    title: "State of Lagos Roads: Our Community Survey Report",
    slug: "state-of-lagos-roads-community-survey-2026",
    excerpt: "Our latest community survey reveals that 68% of Lagos residents rate road conditions in their neighbourhoods as 'poor' or 'very poor'. Here are the full findings.",
    content: `<p>Eko Club Philadelphia conducted a comprehensive survey of road conditions across Lagos State, gathering data from over 3,000 respondents in 15 LGAs between January and March 2026.</p><h2>Key Findings</h2><ul><li>68% of respondents rate local road conditions as 'poor' or 'very poor'</li><li>Alimosho and Mushin LGAs scored worst, with over 80% negative ratings</li><li>Victoria Islandâ€“Lekki axis rated best, with 45% positive ratings</li><li>Over 70% say poor roads negatively impact their daily productivity</li></ul><p>The full report has been submitted to the Lagos State Ministry of Works and will be presented at the upcoming Town Hall.</p>`,
    category: "report",
    status: "published",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    authorId: "u-admin-002",
    authorName: "Amaka Eze",
    authorAvatarUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Amaka",
    viewCount: 3210,
    readingTimeMinutes: 6,
    isFeatured: true,
    isBreaking: false,
    isPinned: false,
    tags: ["infrastructure", "roads", "survey", "report", "lagos"],
    publishedAt: "2026-04-20T08:00:00.000Z",
    createdAt: "2026-04-18T08:00:00.000Z",
    updatedAt: "2026-04-20T08:00:00.000Z",
  },
  {
    id: "news-003",
    title: "BREAKING: Lagos INEC Office Partners with ECP on Voter Registration Drive",
    slug: "inec-ecp-voter-registration-partnership-2026",
    excerpt: "The Lagos State INEC office has officially partnered with Eko Club Philadelphia to coordinate a voter registration drive targeting first-time voters ahead of 2027 elections.",
    content: `<p>In a significant development for community participation in Lagos, the Independent National Electoral Commission (INEC) Lagos office has signed a Memorandum of Understanding with Eko Club Philadelphia for a coordinated voter registration drive.</p><p>The partnership targets 100,000 new voter registrations before the 2027 general elections, with a focus on youth aged 18â€“30 who are yet to register.</p><p>"This partnership validates the work ECP has been doing on the ground," said Secretary-General Amaka Eze. "INEC recognizes us as a credible partner because of our community trust."</p>`,
    category: "news",
    status: "published",
    imageUrl: "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=800",
    authorId: "u-admin-001",
    authorName: "Chidi Okonkwo",
    viewCount: 5621,
    readingTimeMinutes: 4,
    isFeatured: true,
    isBreaking: true,
    isPinned: false,
    tags: ["inec", "voter-registration", "elections", "partnership"],
    publishedAt: "2026-05-03T08:00:00.000Z",
    createdAt: "2026-05-03T07:00:00.000Z",
    updatedAt: "2026-05-03T09:00:00.000Z",
  },
  {
    id: "news-004",
    title: "Youth Empowerment Forum Draws 400 Participants",
    slug: "youth-empowerment-forum-400-participants",
    excerpt: "ECP's Youth Empowerment Forum held last weekend attracted over 400 young Lagosians eager to learn about civic engagement and career development.",
    content: `<p>Eko Club Philadelphia's Youth Empowerment Forum, held at the University of Lagos conference centre on April 26â€“27, drew an impressive crowd of over 400 young participants from across the state.</p><p>Sessions covered civic literacy, entrepreneurship, digital skills, and mental health awareness. Keynote speakers included young entrepreneurs, community leaders, and a serving lawmaker.</p><p>Participant Bisola Okafor, 22, said: "I came without knowing what to expect and I'm leaving with a roadmap for how I can make a difference in my community."</p>`,
    category: "news",
    status: "published",
    imageUrl: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800",
    authorId: "u-member-003",
    authorName: "Emeka Uche",
    authorAvatarUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Emeka",
    viewCount: 2104,
    readingTimeMinutes: 4,
    isFeatured: false,
    isBreaking: false,
    isPinned: false,
    tags: ["youth", "forum", "empowerment", "university"],
    publishedAt: "2026-04-29T08:00:00.000Z",
    createdAt: "2026-04-28T08:00:00.000Z",
    updatedAt: "2026-04-29T08:00:00.000Z",
  },
  {
    id: "news-005",
    title: "Opinion: Why cultural education Must Start in Primary School",
    slug: "opinion-civic-education-primary-school",
    excerpt: "Waiting until university to teach civic responsibility is too late. A Lagos teacher makes the case for mandatory cultural education from age six.",
    content: `<p>By Emeka Uche, Eko Club Philadelphia Member and Secondary School Teacher</p><p>Every election cycle, we hear the same lament: Nigerians don't understand how their democracy works. Politicians sell their votes for pennies. Young people don't register. But what if the problem is older than the voters themselves?</p><p>As a teacher in Lagos, I see daily how civic knowledge is absent from our curriculum. Children memorise the capital cities of Burkina Faso but cannot name their local government chairman or describe what a ward councillor does...</p>`,
    category: "opinion",
    status: "published",
    authorId: "u-member-003",
    authorName: "Emeka Uche",
    authorAvatarUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Emeka",
    viewCount: 1876,
    readingTimeMinutes: 7,
    isFeatured: false,
    isBreaking: false,
    isPinned: false,
    tags: ["opinion", "education", "civic", "schools", "reform"],
    publishedAt: "2026-04-15T08:00:00.000Z",
    createdAt: "2026-04-14T08:00:00.000Z",
    updatedAt: "2026-04-15T08:00:00.000Z",
  },
  {
    id: "news-006",
    title: "ECP Joins Coalition Against Illegal Waste Dumping in Lagos Waterways",
    slug: "ecp-coalition-illegal-waste-lagos-waterways",
    excerpt: "Eko Club Philadelphia has joined a 12-organisation coalition demanding immediate action against illegal waste into Lagos waterways ahead of the rainy season.",
    content: `<p>Eko Club Philadelphia has joined a coalition of twelve organisations to demand immediate government action against illegal waste disposal into Lagos waterways. The wet season, which begins in April, annually transforms many Lagos streets into rivers due in part to blocked drainage channels.</p><p>The coalition has delivered a formal petition to the Lagos State Ministry of Environment and submitted Freedom of Information requests to three LGAs.</p>`,
    category: "news",
    status: "published",
    imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800",
    authorId: "u-member-004",
    authorName: "Fatima Sule",
    viewCount: 987,
    readingTimeMinutes: 3,
    isFeatured: false,
    isBreaking: false,
    isPinned: false,
    tags: ["environment", "waterways", "coalition", "advocacy"],
    publishedAt: "2026-04-08T08:00:00.000Z",
    createdAt: "2026-04-07T08:00:00.000Z",
    updatedAt: "2026-04-08T08:00:00.000Z",
  },
  {
    id: "news-007",
    title: "Annual Report 2025: Measuring Our Impact",
    slug: "ecp-annual-report-2025",
    excerpt: "Our 2025 annual report is now available. Read about our impact: 12,000 people reached, 22 events held, and â‚¦8.2 million raised for community projects.",
    content: `<p>Eko Club Philadelphia is proud to present our 2025 Annual Impact Report. This year was transformational for our organisation and for the communities we serve.</p><h2>By the Numbers</h2><ul><li>12,847 Lagos residents reached through programmes</li><li>22 events held across 10 LGAs</li><li>â‚¦8.2 million raised and deployed for community projects</li><li>340 active members at year-end</li><li>6 policy submissions accepted by Lagos State government</li></ul>`,
    category: "report",
    status: "published",
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
    authorId: "u-admin-002",
    authorName: "Amaka Eze",
    viewCount: 2453,
    readingTimeMinutes: 8,
    isFeatured: false,
    isBreaking: false,
    isPinned: false,
    tags: ["annual-report", "impact", "transparency", "2025"],
    publishedAt: "2026-01-31T08:00:00.000Z",
    createdAt: "2026-01-28T08:00:00.000Z",
    updatedAt: "2026-01-31T08:00:00.000Z",
  },
];

/* â”€â”€â”€ Committees â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
export const SEED_COMMITTEES: Committee[] = [
  {
    id: "com-001",
    name: "Executive Committee",
    slug: "executive-committee",
    description: "The governing body of Eko Club Philadelphia, responsible for strategic direction, major decisions, and organisational oversight.",
    type: "executive",
    status: "active",
    mandate: "Provide strategic leadership, approve budgets, and represent Eko Club Philadelphia externally.",
    members: [
      {
        userId: "u-admin-001",
        name: "Chidi Okonkwo",
        role: "Chairperson",
        isChairperson: true,
        isViceChair: false,
        joinedCommitteeAt: "2023-01-15T08:00:00.000Z",
        socialLinks: [{ platform: "twitter", url: "https://twitter.com/chidiokonkwo" }],
        bio: "Founding Chair of Eko Club Philadelphia. 15+ years in civic engagement.",
        imageUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Chidi",
      },
      {
        userId: "u-admin-002",
        name: "Amaka Eze",
        role: "Secretary-General",
        isChairperson: false,
        isViceChair: false,
        joinedCommitteeAt: "2023-02-10T08:00:00.000Z",
        socialLinks: [{ platform: "linkedin", url: "https://linkedin.com/in/amakaeze" }],
        bio: "Secretary-General overseeing day-to-day operations.",
        imageUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Amaka",
      },
      {
        userId: "u-member-002",
        name: "Ngozi Obi",
        role: "Legal Advisor",
        isChairperson: false,
        isViceChair: false,
        joinedCommitteeAt: "2023-10-01T08:00:00.000Z",
        bio: "Legal Advisor to the Executive Committee.",
        imageUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Ngozi",
      },
    ],
    establishedAt: "2023-01-15T08:00:00.000Z",
    createdAt: "2023-01-15T08:00:00.000Z",
    updatedAt: "2026-01-01T08:00:00.000Z",
  },
  {
    id: "com-002",
    name: "cultural education Committee",
    slug: "civic-education-committee",
    description: "Designs and delivers cultural education programmes for Lagos communities, schools, and youth groups.",
    type: "standing",
    status: "active",
    mandate: "Develop curriculum, run training programmes, and coordinate school outreach.",
    members: [
      {
        userId: "u-member-003",
        name: "Emeka Uche",
        role: "Chairperson",
        isChairperson: true,
        isViceChair: false,
        joinedCommitteeAt: "2023-11-01T08:00:00.000Z",
        bio: "Secondary school teacher and cultural education advocate.",
        imageUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Emeka",
      },
      {
        userId: "u-member-004",
        name: "Fatima Sule",
        role: "Vice Chairperson",
        isChairperson: false,
        isViceChair: true,
        joinedCommitteeAt: "2024-02-01T08:00:00.000Z",
        bio: "Public health worker bridging health and civic advocacy.",
        imageUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Fatima",
      },
      {
        name: "Biodun Fashola",
        role: "Member",
        isChairperson: false,
        isViceChair: false,
        joinedCommitteeAt: "2024-03-01T08:00:00.000Z",
        bio: "Curriculum developer and trainer.",
        imageUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Biodun",
      },
    ],
    establishedAt: "2023-05-01T08:00:00.000Z",
    createdAt: "2023-05-01T08:00:00.000Z",
    updatedAt: "2026-01-01T08:00:00.000Z",
  },
  {
    id: "com-003",
    name: "Legal & Advocacy Committee",
    slug: "legal-advocacy-committee",
    description: "Handles legal matters, rights advocacy, policy submissions, and electoral law education.",
    type: "standing",
    status: "active",
    mandate: "Provide legal guidance, draft policy submissions, and advocate for members' civic rights.",
    members: [
      {
        userId: "u-member-002",
        name: "Ngozi Obi",
        role: "Chairperson",
        isChairperson: true,
        isViceChair: false,
        joinedCommitteeAt: "2023-09-01T08:00:00.000Z",
        bio: "Electoral law specialist and legal practitioner.",
        imageUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Ngozi",
        socialLinks: [{ platform: "linkedin", url: "https://linkedin.com/in/ngoziobilaw" }],
      },
      {
        name: "Seun Adesanya",
        role: "Member",
        isChairperson: false,
        isViceChair: false,
        joinedCommitteeAt: "2024-01-01T08:00:00.000Z",
        bio: "Constitutional law expert.",
        imageUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Seun",
      },
    ],
    establishedAt: "2023-06-01T08:00:00.000Z",
    createdAt: "2023-06-01T08:00:00.000Z",
    updatedAt: "2025-06-01T08:00:00.000Z",
  },
  {
    id: "com-004",
    name: "Technology & Innovation Committee",
    slug: "technology-innovation-committee",
    description: "Drives digital transformation within Eko Club Philadelphia, including the platform, digital campaigns, and data analytics.",
    type: "standing",
    status: "active",
    mandate: "Maintain digital infrastructure, develop tech-for-civic projects, and upskill members.",
    members: [
      {
        userId: "u-member-001",
        name: "Tunde Adeyemi",
        role: "Chairperson",
        isChairperson: true,
        isViceChair: false,
        joinedCommitteeAt: "2023-07-01T08:00:00.000Z",
        bio: "Software engineer leading ECP's digital transformation.",
        imageUrl: "https://api.dicebear.com/8.x/avataaars/svg?seed=Tunde",
        socialLinks: [
          { platform: "twitter", url: "https://twitter.com/tundeadeyemi" },
          { platform: "linkedin", url: "https://linkedin.com/in/tundeadeyemi" },
        ],
      },
    ],
    establishedAt: "2023-07-01T08:00:00.000Z",
    createdAt: "2023-07-01T08:00:00.000Z",
    updatedAt: "2025-12-01T08:00:00.000Z",
  },
];

/* â”€â”€â”€ Products â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
export const SEED_PRODUCTS: Product[] = [
  {
    id: "prod-001",
    name: "Eko Club Philadelphia T-Shirt (Green)",
    slug: "ecp-lagos-tshirt-green",
    description: "Show your civic pride with our official Eko Club Philadelphia T-Shirt. 100% cotton, comfortable fit, with the ECP logo printed in gold on the front.",
    shortDescription: "Official Eko Club Philadelphia T-Shirt in Lagos green.",
    price: 5000,
    category: "apparel",
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600",
    stock: 150,
    sku: "ECP-TS-GRN-001",
    tags: ["merchandise", "apparel", "t-shirt"],
    isFeatured: true,
    isMemberOnly: false,
    createdAt: "2025-01-15T08:00:00.000Z",
    updatedAt: "2026-03-01T08:00:00.000Z",
  },
  {
    id: "prod-002",
    name: "Eko Club Philadelphia Cap",
    slug: "ecp-lagos-cap",
    description: "Structured six-panel cap in Lagos green with gold ECP emblem. One size fits most with adjustable strap.",
    shortDescription: "Official Eko Club Philadelphia cap in signature green and gold.",
    price: 3500,
    category: "accessories",
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600",
    stock: 80,
    tags: ["merchandise", "accessories", "cap"],
    isFeatured: false,
    isMemberOnly: false,
    createdAt: "2025-01-15T08:00:00.000Z",
    updatedAt: "2026-01-01T08:00:00.000Z",
  },
  {
    id: "prod-003",
    name: "Civic Rights Handbook 2026",
    slug: "civic-rights-handbook-2026",
    description: "The Eko Club Philadelphia Civic Rights Handbook â€” a comprehensive guide to your rights as a Lagos resident and Nigerian citizen. Covers electoral rights, land rights, consumer rights, and how to access public services.",
    shortDescription: "Complete guide to your rights as a Lagos resident.",
    price: 2500,
    compareAtPrice: 3500,
    category: "publications",
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600",
    stock: 300,
    tags: ["book", "rights", "civic", "publication"],
    isFeatured: true,
    isMemberOnly: false,
    createdAt: "2026-01-15T08:00:00.000Z",
    updatedAt: "2026-04-01T08:00:00.000Z",
  },
  {
    id: "prod-004",
    name: "ECP Members Tote Bag",
    slug: "ecp-members-tote-bag",
    description: "Durable canvas tote bag with the Eko Club Philadelphia crest. Perfect for carrying your documents and spreading civic awareness.",
    price: 2000,
    category: "accessories",
    status: "active",
    imageUrl: "https://images.unsplash.com/photo-1591085686350-798c0f9faa7f?w=600",
    stock: 100,
    tags: ["merchandise", "tote", "bag"],
    isFeatured: false,
    isMemberOnly: false,
    createdAt: "2025-06-01T08:00:00.000Z",
    updatedAt: "2026-01-01T08:00:00.000Z",
  },
  {
    id: "prod-005",
    name: "Digital Civic Starter Kit",
    slug: "digital-civic-starter-kit",
    description: "A curated digital download package for new members: PDF handbook, editable letter templates for writing to government officials, voters guide, and 3-month access to members-only resources.",
    price: 1500,
    category: "digital",
    status: "active",
    stock: 999,
    tags: ["digital", "download", "starter-kit", "members"],
    isFeatured: false,
    isMemberOnly: true,
    createdAt: "2026-02-01T08:00:00.000Z",
    updatedAt: "2026-04-01T08:00:00.000Z",
  },
];

/* â”€â”€â”€ Orders â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
export const SEED_ORDERS: Order[] = [
  {
    id: "ord-001",
    orderNumber: "ECP-2026-0001",
    userId: "u-member-001",
    customerName: "Tunde Adeyemi",
    customerEmail: "tunde.adeyemi@email.com",
    items: [
      {
        productId: "prod-001",
        productName: "Eko Club Philadelphia T-Shirt (Green)",
        price: 5000,
        quantity: 2,
        subtotal: 10000,
      },
      {
        productId: "prod-002",
        productName: "Eko Club Philadelphia Cap",
        price: 3500,
        quantity: 1,
        subtotal: 3500,
      },
    ],
    subtotal: 13500,
    shippingFee: 1500,
    discount: 0,
    total: 15000,
    shippingAddress: {
      fullName: "Tunde Adeyemi",
      phone: "08034567890",
      address: "45 Bode Thomas Street",
      city: "Surulere",
      state: "Lagos",
      country: "Nigeria",
    },
    paymentMethod: "card",
    paymentStatus: "paid",
    paymentReference: "PAY-REF-20260115001",
    status: "delivered",
    createdAt: "2026-01-15T10:00:00.000Z",
    updatedAt: "2026-01-22T14:00:00.000Z",
    confirmedAt: "2026-01-15T11:00:00.000Z",
    shippedAt: "2026-01-18T09:00:00.000Z",
    deliveredAt: "2026-01-22T14:00:00.000Z",
  },
  {
    id: "ord-002",
    orderNumber: "ECP-2026-0002",
    userId: "u-member-002",
    customerName: "Ngozi Obi",
    customerEmail: "ngozi.obi@email.com",
    items: [
      {
        productId: "prod-003",
        productName: "Civic Rights Handbook 2026",
        price: 2500,
        quantity: 3,
        subtotal: 7500,
        imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600",
      },
    ],
    subtotal: 7500,
    shippingFee: 1000,
    discount: 0,
    total: 8500,
    shippingAddress: {
      fullName: "Ngozi Obi",
      phone: "08045678901",
      address: "12 Akin Adesola Street",
      city: "Victoria Island",
      state: "Lagos",
      country: "Nigeria",
    },
    paymentMethod: "bank-transfer",
    paymentStatus: "paid",
    paymentReference: "PAY-REF-20260210001",
    status: "delivered",
    createdAt: "2026-02-10T10:00:00.000Z",
    updatedAt: "2026-02-20T14:00:00.000Z",
    confirmedAt: "2026-02-11T09:00:00.000Z",
    shippedAt: "2026-02-14T10:00:00.000Z",
    deliveredAt: "2026-02-20T14:00:00.000Z",
  },
  {
    id: "ord-003",
    orderNumber: "ECP-2026-0003",
    userId: "u-member-004",
    customerName: "Fatima Sule",
    customerEmail: "fatima.sule@email.com",
    items: [
      {
        productId: "prod-001",
        productName: "Eko Club Philadelphia T-Shirt (Green)",
        price: 5000,
        quantity: 1,
        subtotal: 5000,
      },
      {
        productId: "prod-004",
        productName: "ECP Members Tote Bag",
        price: 2000,
        quantity: 1,
        subtotal: 2000,
      },
    ],
    subtotal: 7000,
    shippingFee: 1000,
    discount: 0,
    total: 8000,
    shippingAddress: {
      fullName: "Fatima Sule",
      phone: "08067890123",
      address: "28 Owode Street",
      city: "Kosofe",
      state: "Lagos",
      country: "Nigeria",
    },
    paymentMethod: "card",
    paymentStatus: "paid",
    status: "shipped",
    paymentReference: "PAY-REF-20260430001",
    createdAt: "2026-04-30T10:00:00.000Z",
    updatedAt: "2026-05-02T11:00:00.000Z",
    confirmedAt: "2026-04-30T11:00:00.000Z",
    shippedAt: "2026-05-02T11:00:00.000Z",
  },
  {
    id: "ord-004",
    orderNumber: "ECP-2026-0004",
    userId: "u-member-003",
    customerName: "Emeka Uche",
    customerEmail: "emeka.uche@email.com",
    items: [
      {
        productId: "prod-003",
        productName: "Civic Rights Handbook 2026",
        price: 2500,
        quantity: 5,
        subtotal: 12500,
      },
    ],
    subtotal: 12500,
    shippingFee: 1500,
    discount: 500,
    total: 13500,
    shippingAddress: {
      fullName: "Emeka Uche",
      phone: "08056789012",
      address: "7 Idimu Road",
      city: "Alimosho",
      state: "Lagos",
      country: "Nigeria",
    },
    paymentMethod: "card",
    paymentStatus: "unpaid",
    status: "pending",
    createdAt: "2026-05-04T10:00:00.000Z",
    updatedAt: "2026-05-04T10:00:00.000Z",
  },
];

/* â”€â”€â”€ Donations â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
export const SEED_DONATIONS: Donation[] = [
  {
    id: "don-001",
    referenceNumber: "DON-2026-0001",
    userId: "u-member-001",
    donorName: "Tunde Adeyemi",
    donorEmail: "tunde.adeyemi@email.com",
    donorPhone: "08034567890",
    isAnonymous: false,
    amount: 50000,
    type: "one-time",
    cause: "civic-education",
    message: "Keep up the amazing work educating Lagosians!",
    paymentMethod: "card",
    paymentReference: "DON-PAY-20260115001",
    status: "successful",
    isRecurring: false,
    acknowledgedAt: "2026-01-16T08:00:00.000Z",
    acknowledgedBy: "u-admin-001",
    createdAt: "2026-01-15T12:00:00.000Z",
    updatedAt: "2026-01-16T08:00:00.000Z",
  },
  {
    id: "don-002",
    referenceNumber: "DON-2026-0002",
    userId: "u-member-002",
    donorName: "Ngozi Obi",
    donorEmail: "ngozi.obi@email.com",
    isAnonymous: false,
    amount: 100000,
    type: "one-time",
    cause: "youth-empowerment",
    message: "For the youth who will lead tomorrow's Lagos.",
    paymentMethod: "bank-transfer",
    paymentReference: "DON-PAY-20260220001",
    status: "successful",
    isRecurring: false,
    acknowledgedAt: "2026-02-22T08:00:00.000Z",
    acknowledgedBy: "u-admin-002",
    createdAt: "2026-02-20T14:00:00.000Z",
    updatedAt: "2026-02-22T08:00:00.000Z",
  },
  {
    id: "don-003",
    referenceNumber: "DON-2026-0003",
    donorName: "Anonymous Donor",
    donorEmail: "anon@private.com",
    isAnonymous: true,
    amount: 25000,
    type: "one-time",
    cause: "environmental",
    status: "successful",
    isRecurring: false,
    createdAt: "2026-03-10T10:00:00.000Z",
    updatedAt: "2026-03-10T10:00:00.000Z",
  },
  {
    id: "don-004",
    referenceNumber: "DON-2026-0004",
    userId: "u-member-004",
    donorName: "Fatima Sule",
    donorEmail: "fatima.sule@email.com",
    isAnonymous: false,
    amount: 10000,
    type: "monthly",
    cause: "healthcare",
    message: "Every monthly contribution is a step towards better health for Lagos communities.",
    paymentMethod: "card",
    paymentReference: "DON-PAY-20260401001",
    status: "successful",
    isRecurring: true,
    nextChargeDate: "2026-06-01T00:00:00.000Z",
    createdAt: "2026-04-01T12:00:00.000Z",
    updatedAt: "2026-04-01T12:00:00.000Z",
  },
  {
    id: "don-005",
    referenceNumber: "DON-2026-0005",
    userId: "u-member-003",
    donorName: "Emeka Uche",
    donorEmail: "emeka.uche@email.com",
    isAnonymous: false,
    amount: 15000,
    type: "one-time",
    cause: "education",
    status: "successful",
    isRecurring: false,
    createdAt: "2026-04-15T10:00:00.000Z",
    updatedAt: "2026-04-15T10:00:00.000Z",
  },
  {
    id: "don-006",
    referenceNumber: "DON-2026-0006",
    donorName: "Oluwaseun Martins",
    donorEmail: "seun.martins@email.com",
    isAnonymous: false,
    amount: 200000,
    type: "one-time",
    cause: "general",
    message: "From a proud Lagosian based in Abuja. Keep flying the flag!",
    paymentMethod: "bank-transfer",
    status: "pending",
    isRecurring: false,
    createdAt: "2026-05-04T16:00:00.000Z",
    updatedAt: "2026-05-04T16:00:00.000Z",
  },
];

